<a href="https://colab.research.google.com/github/jailtonCosta/Projetos_Colab/blob/main/Imersao_IA_Alura_%2B_Google_aula5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install -U -q google-generativeai

In [ ]:
import numpy as np
import pandas as pd
import google.generativeai  as genai

GOOGLE_API_KEY= "AIzaSyCF5DThRRMe8Z3w-T2-aXqyqTGp95s76ug"
genai.configure(api_key=GOOGLE_API_KEY)

In [ ]:
for m in genai.list_models():
  if 'embedContent' in m.supported_generation_methods:
    print(m.name)

models/embedding-001
models/text-embedding-004

In [ ]:
title = "Felicidade e bem Estar"
sample_text = (" Titulo : Felicidade e bem Estar"
"\n"
"Artigo Completo : \n"
"\n"
    "Felicidade e bem-estar:muitas pessoas acreditam que o objetivo da vida é ter felicidade e bem-estar pessoal. "
   " Isso pode envolver localizar atividades que proporcionem alegria, estabelecer conexões significativas, cuidar da saúde física e mental da pessoa e buscar objetivos e interesses pessoais."
   " Contribuição significativa:algumas pessoas acreditam que o propósito da vida é fazer uma contribuição significativa para o mundo. Isso pode incluir o exercício de uma profissão que beneficie outras pessoas, o envolvimento em atividades voluntárias ou beneficentes, geração de arte ou literatura ou invenções.")

embeddings = genai.embed_content(model= "models/embedding-001",
                                content = sample_text ,
                                title = title,
                                task_type= "RETRIEVAL_DOCUMENT")

print(embeddings)

{'embedding': [0.019746779, -0.022032507, -0.025473848, 0.005712378, 0.050944414, 0.020230763, -0.0109122805, -0.026711572, 0.029857196, 0.06871565, -0.020402124, 0.013283391, 0.023805462, -0.020689765, -0.0148777515, -0.011911577, -0.0048187748, -0.0030594207, -0.022468088, -0.05383552, -0.016867334, -0.018430196, -0.030860618, -0.04032588, 0.0034337007, -0.014334956, 0.00969362, -0.051090714, 0.020709453, 0.056452226, -0.04972545, 0.08178668, -0.085179165, -0.00031294933, 0.024909403, -0.02928289, -0.022473747, -0.017628351, -0.029099677, 0.019578317, -0.016312374, -0.04974269, -0.03383908, -0.014514985, -0.010355297, -0.003970556, -0.015488454, 0.048638072, -0.0019067228, -0.0777804, 0.003106069, 0.038105853, 0.087180674, -0.0029668948, -0.00063941296, -0.0021348018, 0.030761559, -0.010718585, -0.0137141915, 0.029427567, -0.01609885, -0.04612073, 0.080041125, 0.07946976, 0.0026724432, -0.025172392, 0.014038903, -0.014957893, 0.05111558, 0.0037135489, -0.0200925, -0.032554727, 0.0067237094, 0.019841135, 0.011361591, -0.051584627, -0.030409059, 0.07980266, -0.02454514, -0.009921186, -0.020664005, -0.06323032, -0.021327117, -0.02341824, -0.06274027, 0.032433473, -0.08134414, 0.013270296, 0.0063918335, 0.028209103, -0.02841976, -0.016683627, 0.027135493, -0.032647446, 0.0021291245, 0.070002876, -0.08800336, -0.040874284, -0.0003143213, -0.03183442, 0.045161735, -0.016926419, -0.09700625, 0.004502146, -0.007035821, 0.011892197, -0.0065786135, 0.020657592, 0.052237384, 0.09272385, -0.02708668, -0.0020395238, 0.013009266, 0.016291052, 0.034385033, -0.02617899, -0.009615757, 0.055499695, 0.0233642, 0.042237338, 0.00418953, 0.051220767, 0.09070777, -0.008546523, -0.030513413, -0.0015612862, -0.0072283586, 0.032542072, 0.056576367, 0.01251696, 0.037534848, -0.043141674, 0.0027282077, 0.019078428, 0.07621535, 0.05384312, 0.03574431, -0.030960985, 0.066498436, 0.02629831, -0.009993014, -0.0069761476, 0.010139426, 0.018466469, -0.054495566, 0.056119364, 0.008870505, -0.028433448, 0.03938143, -0.016159965, 0.02401418, -0.011252306, -0.08272618, 0.014957088, 0.13564573, 0.03459177, 0.025723837, 0.025514815, 0.040621914, 0.024243936, 0.054243103, 0.02869223, -0.03669482, 0.052326776, -0.034955397, -0.058782004, -0.029433044, -0.03262817, 0.04486946, 0.037538167, 0.022880362, 0.030138887, -0.035963606, -0.045977138, -0.010324814, -0.01844515, -0.007660957, 0.026606519, -0.05173744, -0.0021127022, -0.001958137, -0.032843236, -0.0074255876, 0.005464922, 0.03760013, -0.032419443, 0.043253545, -0.035810526, -0.050483316, 0.021043124, 0.014981722, -0.044995267, -0.019259771, -0.0031898739, -0.034519386, 0.026207272, -0.0032282723, 0.02933932, 0.022299401, -0.034132358, 0.013087511, 0.08228913, 0.009153744, -0.039024975, -0.034562394, -0.020174086, 0.048375715, -0.04577233, -0.04192233, 0.041180633, -0.07209249, -0.0089372825, 0.01534384, 0.025245892, 0.012172184, 0.026226977, -0.005368933, 0.015810864, 0.02738484, -0.09067466, -0.03643442, 0.032670923, -0.075497225, -0.00032966802, -0.04227037, 0.037273005, -0.02582894, 0.025720194, 0.007610447, -0.04996277, 0.026153335, 0.03991222, 0.038383346, 0.00587229, 0.048443735, -0.041040238, 0.077611536, 0.038734347, -0.035208777, 0.030780613, -0.01590865, 0.029371418, 0.051127505, 0.04923749, -0.04149131, 0.017417144, -0.051599763, 0.01922382, -0.038701672, 0.026888652, -0.0051208753, -0.039792344, -0.034400776, 0.03028238, -0.04235498, 0.00070241414, -0.015683508, -0.023187188, 0.03293973, -0.01375782, 0.10204792, 0.030226517, 0.051531922, 0.023941243, -0.051492453, -0.016178675, 0.024007797, -0.05194601, 0.029118393, 0.03737777, 0.023740882, -0.0033026505, 0.06915803, -0.02344013, -0.024238508, -0.0030205087, -0.0017432013, 0.038249005, 0.024849804, -0.04129196, 0.01137591, 0.010120032, 0.05607478, -0.011973873, 0.006414874, -0.026764821, -0.11104474, -0.045199987, 0.007776302, -0.06095147, -0.026655355, -0.0051594707, 0.012965867, -0.027754132, -0.08375229, 0.00047321047, 0.0009183967, 0.0060044453, 0.03389917, -0.02697796, -0.012301393, -0.03863085, 0.027937587, -0.07723681, -0.0072709173, -0.009284118, 0.021123871, 0.01581715, -0.004950493, 0.029911296, 0.0008587831, -0.028681492, -0.0344836, 0.00496554, 0.04210251, 0.058183614, 0.0010394007, 0.011241187, -0.046548776, 0.054809872, 0.018677214, 0.06201448, 0.047204904, 0.043035403, -0.016468165, -0.00065008324, 0.023615059, 0.015742708, 0.038207386, 0.051566713, 0.013144717, -0.07608873, -0.009186977, 0.009461911, 0.012914654, 0.022352803, -0.051127672, 0.036072243, -0.021766102, 0.013548893, 0.025763309, -0.025439948, -0.006102645, -0.002857604, 0.020024737, 0.019256758, -0.01071153, 0.027709635, 0.020039937, 0.0045149173, -0.0039379797, 0.0045597465, 0.015870024, 0.023535399, 0.0093372315, -0.034950458, 0.019221978, -0.021641368, 0.046651673, -0.0005737187, -0.032101452, 0.057300944, -0.024317868, -0.026885265, -0.011950423, 0.01567858, 0.001505393, -0.002677294, -0.020993672, 0.054527704, 0.031183185, -0.041319657, 0.036607202, -0.017808998, 0.009327225, -0.021446122, 0.003157635, -0.049321014, 0.042773634, 0.015008988, -0.039912757, -0.050417513, 0.043153893, 0.026513953, -0.016677078, -0.0061290907, 0.05185181, 0.01581726, 0.0030030692, 0.048679747, 0.0043842127, -0.014033843, 0.09123555, 0.0035914993, 0.012283073, -0.045132726, -0.02526677, -0.022829851, 0.012347877, 0.0021966835, 0.015203765, -0.020877322, 0.002463936, -0.007784511, -0.013277522, 0.017327031, -0.018830962, -0.0080446955, -0.007641912, 0.009649813, -0.0006941176, 0.007721703, 0.025276607, -0.055746544, -0.05037034, -0.0023075577, 0.014670516, -0.015296869, 0.0066174967, -0.05067485, -0.023329973, -0.029312616, -0.0018402997, 0.031856198, -0.055587046, -0.044362493, 0.014386305, -0.061462127, 0.01801991, -0.02817239, 0.04378871, -0.019181205, 0.028319698, -0.0049287984, -0.011004439, -0.038823772, 0.008618416, 0.016895926, 0.02047577, -0.028077064, -0.0053708195, -0.009623793, 0.07646051, -0.011130238, -0.052547976, -0.010431052, 0.019533351, -0.02947068, 0.0085623255, -0.054741126, 0.019563178, -0.033963308, -0.016949404, -0.049579363, 0.03471473, 0.029053671, -0.0022778737, 0.029414732, -0.018080126, 0.024133151, -0.020985447, -0.062343817, 0.005896867, -0.06511926, 0.0059907115, 0.048203897, 0.0058023585, 0.02795036, 0.0058495044, 0.07108503, 0.02330234, -0.06705623, 0.073438324, -0.032188334, 0.03262109, -0.0032034563, -0.043648396, -0.013600055, -0.06213951, -0.019439392, -0.010577135, -0.03892875, 0.026243385, 0.027119555, -0.010306402, 0.0030098783, -0.011413806, 0.013245016, 0.028104864, 0.07412834, -0.029855138, -0.031619586, -0.016555753, -0.075701505, -0.03403488, 0.036365047, -0.082767, 0.019857893, -0.01235374, 0.031549238, 0.0027659924, 0.010561952, 0.004619396, -0.016779553, 0.047052033, -0.046079397, 0.021069866, 0.003461243, -0.017167624, -0.016023563, 0.011401335, -0.0150315175, 0.0067662233, 0.00070909807, 0.05693096, 0.0031690542, 0.0127796745, -0.0052611167, 0.019092163, -0.022452787, -0.010650707, -0.02359299, -0.09850284, -0.010499746, 0.03710337, -0.057150498, -0.0094837155, 0.029956114, 0.018411716, -0.0035070486, -0.06075872, 0.043993507, -0.031834673, 0.006434065, 0.017691486, 0.005053468, 0.045733087, 0.058760997, 0.032591127, 0.030516732, 0.016012928, 0.009101815, 0.075326025, 0.061929334, 0.001960044, 0.024322212, 0.009905223, -0.08202939, 0.00471112, 0.012436023, 0.0018267246, -0.03757868, 0.015944107, -0.002186606, 0.03612436, 0.044312436, 0.012305387, 0.035957947, 0.020230768, -0.015918616, -0.00056279503, 0.030631687, -0.03205094, -0.022247488, 0.08395021, 0.049512852, -0.04207127, 0.0014349982, 0.03026031, -0.039360527, 0.0035841474, 0.039292146, 0.039902072, -0.016073719, 0.009361216, -0.0066290963, -0.014709932, -0.019277103, -0.042196695, -0.010942572, 0.013134426, -0.00046974508, -0.002931125, 0.012257557, 0.01585245, 0.054803856, 0.03957244, 0.024665339, 0.033921644, 0.022006063, -0.035931904, 0.0550857, 0.018710094, 0.025790777, -0.003645188, -0.018002152, 0.039674405, -0.035070904, -0.023751225, -0.020959191, 0.0023283677, -0.026249593, 0.06932117, -0.021660103, 0.023438016, 0.034478642, 0.0009206472, 0.009480845, -0.011824905, 0.0137384115, -0.030160544, -0.025761105, -0.03371386, 0.01722483, -0.057205107, -0.054528482, 0.021505196, 0.030383637, -0.06918602, -0.037199706, 0.011188523, 0.011489212, -0.01135629, 0.03622095, 0.027391437, 0.0070295506, -0.037974294, -0.06696083, 0.058170296, 0.039948706, 0.07235256, 0.04306972, 0.035645083, 0.049850877, -0.03998091, -0.021886254, 0.0061365757, 0.004061493, 0.041562255, 0.039848287, -0.026400348, 0.02352083, -0.020327631, 0.0027179678, -0.04345442, 0.10794813, -0.053909212, -0.10098606, -0.06793201, -0.028142918, -0.013829422, 0.013057508, 0.0012915469, -0.008104648, 1.1768075e-05, 0.0021283256, -0.011758257, 0.031053605, 0.018129753, 0.04400983, -0.06071056, 0.00078350445, 0.006992122, -0.024721703, -0.0068203653, -0.029452493, -0.054284308, -0.058850553, -0.012858445, 0.021199143, -0.050963297, -0.030023174, 0.074840106, -0.04651765, -0.0016316625, 0.008245811, -0.07766963, 0.041308504, -0.0043818634, -0.032226775, -0.022633089, -0.07113183, 0.00068898493, -0.02379674, -0.0155839, 0.0074213413, 0.053285196, -0.0043082666, -0.05302534, 0.0063791154, 0.018160095, 0.010355207, 0.00918019, 0.006224676, 0.01635968, -0.0093196975, -0.015882429, -0.013447426, 0.00642017, -0.011191464, 0.029456947, -0.019482192, -0.02652037, 0.013008262, 0.0051866407, -0.01589241, 0.0019773673, 0.0024441238, 0.0453425, 0.06811151, 0.009054831, 0.009908598, -0.034702614, 0.028521646, -0.03296022, -0.061879177, -0.021409342, 0.03602085, -0.005821058, 0.025642712, 0.054125004, 0.006410483, 0.019511178, -0.06995641, -0.05975045, 0.026502922, -0.076556824, 0.03714147, -0.029602682, -0.02963844, 0.07725208, -0.017991371, -0.0022080117, -0.0048878174, -0.05322462, 0.064231984, -0.0210863, 0.008841808, -0.014167732, -0.08547329, -0.039618645, 0.0057940553, 0.0048171347, 0.108556435, 0.026218921, 0.0023303395, -0.020649955, -0.013619441, -0.03941452, -0.029381378, -0.025221102, -0.008209975, 0.057522148, 0.034806527, 0.03237691, 0.016077338, 0.012390873, -0.048544634, 0.010201418, 0.002035961, -0.08375259, -0.0048535136, -0.0029994592, 0.011673101, 0.035328053, 0.031649545, 0.0057353997, 0.01170274]}

In [ ]:
DOCUMENT1 = {
    "Titulo " :  "**Livros**",
    "Conteudo " : "* **Inteligência Artificial: Uma Abordagem Moderna (3ª Edição)** por Stuart Russell e Peter Norvig"
}


DOCUMENT2 = {
    "Titulo " : "**Canais do YouTube**",
    "Conteudo " : "3Blue1Brown:** Vídeos animados explicando conceitos complexos de IA"
}

DOCUMENT3 = {
    "Titulo " : "**Recursos Online**",
    "Conteudo " : "* **Coursera:** Cursos de IA de universidades como Stanford, Google e IBM "
}

documents = [DOCUMENT1,DOCUMENT2, DOCUMENT3]

In [ ]:
df = pd.DataFrame(documents)
df.columns = ["Titulo" , "Conteudo"]
df

                  Titulo                                           Conteudo
0             **Livros**  * **Inteligência Artificial: Uma Abordagem Mod...
1  **Canais do YouTube**  3Blue1Brown:** Vídeos animados explicando conc...
2    **Recursos Online**  * **Coursera:** Cursos de IA de universidades ...

In [ ]:
model = "models/embedding-001"

In [ ]:
def embed_fn (title, text):
  return genai.embed_content(model= model,
                                content = text ,
                                title = title,
                                task_type= "RETRIEVAL_DOCUMENT")["embedding"]

In [ ]:
df ["Embeddings"] = df.apply(lambda row: embed_fn (row["Titulo"], row["Conteudo"]),axis = 1)
df

,Titulo,Conteudo,Embeddings
0,**Livros**,* **Inteligência Artificial: Uma Abordagem Mod...,"[0.0004903961, -0.07978082, -0.030259142, -0.0..."
1,**Canais do YouTube**,3Blue1Brown:** Vídeos animados explicando conc...,"[0.013016549, -0.052729394, -0.039399035, -9.8..."
2,**Recursos Online**,* **Coursera:** Cursos de IA de universidades ...,"[0.04361522, -0.047599826, -0.0069435104, -0.0..."

In [ ]:
def gerar_buscar_consulta (consulta, base, model):
  embedding_da_consulta = genai.embed_content(model= model,
                                content = consulta,
                                task_type= "RETRIEVAL_QUERY")["embedding"]

  produtos_escalares = np.dot(np.stack(df ["Embeddings"]), embedding_da_consulta )
  indice = np.argmax(produtos_escalares)
  return df.iloc[indice]["Conteudo"]

In [ ]:
consulta = "curso de Ia ?"

trecho = gerar_buscar_consulta (consulta, df, model)

print(trecho)

* **Coursera:** Cursos de IA de universidades como Stanford, Google e IBM

In [ ]:
generation_config = {
    "candidate_count" : 1,
    "temperature" : 0.5,

}

prompt = f"Reescreva o texto de forma descotraida ,sem adicionar informacoes que nao fazem parte do texto {trecho}"

model_2 = genai.GenerativeModel("gemini-1.0-pro", generation_config= generation_config )
response = model_2.generate_content(prompt)
print(response.text)

**Coursera: O rolê da Inteligência Artificial**

Tá ligado na IA? A Coursera te dá um rolê pelas melhores aulas de universidades top, como Stanford, Google e IBM. Bora mergulhar no mundo da Inteligência Artificial e ficar fera no assunto!